/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LanDrag {
        "delay": number;
        "dragData": string;
        "dropZones": string;
        "threshold": number;
    }
    interface LanDragImage {
    }
    interface LanDrop {
        "dropZones": string;
    }
}
export interface LanDragCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLanDragElement;
}
declare global {
    interface HTMLLanDragElement extends Components.LanDrag, HTMLStencilElement {
    }
    var HTMLLanDragElement: {
        prototype: HTMLLanDragElement;
        new (): HTMLLanDragElement;
    };
    interface HTMLLanDragImageElement extends Components.LanDragImage, HTMLStencilElement {
    }
    var HTMLLanDragImageElement: {
        prototype: HTMLLanDragImageElement;
        new (): HTMLLanDragImageElement;
    };
    interface HTMLLanDropElement extends Components.LanDrop, HTMLStencilElement {
    }
    var HTMLLanDropElement: {
        prototype: HTMLLanDropElement;
        new (): HTMLLanDropElement;
    };
    interface HTMLElementTagNameMap {
        "lan-drag": HTMLLanDragElement;
        "lan-drag-image": HTMLLanDragImageElement;
        "lan-drop": HTMLLanDropElement;
    }
}
declare namespace LocalJSX {
    interface LanDrag {
        "delay"?: number;
        "dragData"?: string;
        "dropZones"?: string;
        "onDndend"?: (event: LanDragCustomEvent<any>) => void;
        "onDndstart"?: (event: LanDragCustomEvent<any>) => void;
        "threshold"?: number;
    }
    interface LanDragImage {
    }
    interface LanDrop {
        "dropZones"?: string;
    }
    interface IntrinsicElements {
        "lan-drag": LanDrag;
        "lan-drag-image": LanDragImage;
        "lan-drop": LanDrop;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lan-drag": LocalJSX.LanDrag & JSXBase.HTMLAttributes<HTMLLanDragElement>;
            "lan-drag-image": LocalJSX.LanDragImage & JSXBase.HTMLAttributes<HTMLLanDragImageElement>;
            "lan-drop": LocalJSX.LanDrop & JSXBase.HTMLAttributes<HTMLLanDropElement>;
        }
    }
}
